### ISSUE TITLE
account-cli errors with syntax error

### ISSUE THREAD

**Issue by kFuQ** [RetricSu/gw-gitcoin-instruction#3]
When i attempt to make a short address per https://github.com/Kuzirashi/gw-gitcoin-instruction/blob/master/src/component-tutorials/3.setup.and.use.account.cli.md   account-cli creates an error.

```
~/CKB/projects/godwoken-examples$ node ./packages/tools/lib/account-cli.js to-short-address -a 0x9A9A7A95d4d2ce80E97E2079621796e6dC84A77A
/home/derek/CKB/projects/godwoken-examples/packages/tools/lib/account/common.js:30
                console.error(error?.message);
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/derek/CKB/projects/godwoken-examples/packages/tools/lib/account/deposit-ckb.js:12:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal

 node --version
v12.22.5

 yarn --version
1.22.5

![account-cli-error](https://user-images.githubusercontent.com/88947890/130322658-5ab936ed-d1a8-4b5c-b6ec-e2a76f8a0781.png)

**Comment by RetricSu** [comment]
please use node version 14
